In [2]:
import pandas
import os

print(os.getcwd())
food_info = pandas.read_csv('food_info.csv')
print(type(food_info))
print(food_info.dtypes)
print(help(pandas.read_csv))

/home/jing/workspace_py/iUsePython/jupyter
<class 'pandas.core.frame.DataFrame'>
NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)       float64
Iron_(mg)          float64
Magnesium_(mg)     float64
Phosphorus_(mg)    float64
Potassium_(mg)     float64
Sodium_(mg)        float64
Zinc_(mg)          float64
Copper_(mg)        float64
Manganese_(mg)     float64
Selenium_(mcg)     float64
Vit_C_(mg)         float64
Thiamin_(mg)       float64
Riboflavin_(mg)    float64
Niacin_(mg)        float64
Vit_B6_(mg)        float64
Vit_B12_(mcg)      float64
Vit_A_IU           float64
Vit_A_RAE          float64
Vit_E_(mg)         float64
Vit_D_mcg          float64
Vit_D_IU           float64
Vit_K_(mcg)        float64
FA_Sat_(g)         float64
FA_Mono_(g)        float64
FA_Poly_(g)        float64
Cholestrl_(mg)     float64
dtype: object
Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read CSV (comma-separated) file into DataFrame

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the `online docs for IO Tools
    <http://pandas.pydata.org/pandas-docs/stable/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, pathlib.Path, py._path.local.LocalPath or any \
    object with a read() method (such as a file handle or StringIO)
        The string could be a URL. Valid URL schemes include http, ftp, s3, and
        file. For file URLs, a host is expected. For instance, a local file could
        be file://localhost/path/to/table.csv
    sep : str, default ','
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``
    delimiter : str, default ``None``
        Alternative argument name for sep.
    delim_whitespace : boolean, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.

        .. versionadded:: 0.18.1 support for the Python parser.

    header : int or list of ints, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so header=0 denotes the first line of
        data rather than the first line of the file.
    names : array-like, default None
        List of column names to use. If file contains no header row, then you
        should explicitly pass header=None. Duplicates in this list will cause
        a ``UserWarning`` to be issued.
    index_col : int or sequence or False, default None
        Column to use as the row labels of the DataFrame. If a sequence is given, a
        MultiIndex is used. If you have a malformed file with delimiters at the end
        of each line, you might consider index_col=False to force pandas to _not_
        use the first column as the index (row names)
    usecols : list-like or callable, default None
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). For example, a valid list-like
        `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element
        order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : boolean, default False
        If the parsed data only contains one column then return a Series
    prefix : str, default None
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
    mangle_dupe_cols : boolean, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python'}, optional
        Parser engine to use. The C engine is faster while the python engine is
        currently more feature-complete.
    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels
    true_values : list, default None
        Values to consider as True
    false_values : list, default None
        Values to consider as False
    skipinitialspace : boolean, default False
        Skip spaces after delimiter.
    skiprows : list-like or integer or callable, default None
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c')
    nrows : int, default None
        Number of rows of file to read. Useful for reading pieces of large files
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
        'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : boolean, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file
    verbose : boolean, default False
        Indicate number of NA values placed in non-numeric columns
    skip_blank_lines : boolean, default True
        If True, skip over blank lines rather than interpreting as NaN values
    parse_dates : boolean or list of ints or names or list of lists or dict, default False

        * boolean. If True -> try parsing the index.
        * list of ints or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call result
          'foo'

        If a column or index contains an unparseable date, the entire column or
        index will be returned unaltered as an object data type. For non-standard
        datetime parsing, use ``pd.to_datetime`` after ``pd.read_csv``

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : boolean, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : boolean, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, default None
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : boolean, default False
        DD/MM format dates, international and European format
    iterator : boolean, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, default None
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.
    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and
        `filepath_or_buffer` is path-like, then detect compression from the
        following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
        decompression). If using 'zip', the ZIP file must contain only one data
        file to be read in. Set to None for no decompression.

        .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

    thousands : str, default None
        Thousands separator
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    float_precision : string, default None
        Specifies which converter the C engine should use for floating-point
        values. The options are `None` for the ordinary converter,
        `high` for the high-precision converter, and `round_trip` for the
        round-trip converter.
    lineterminator : str (length 1), default None
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : boolean, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), default None
        One-character string used to escape delimiter when quoting is QUOTE_NONE.
    comment : str, default None
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, default None
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_
    dialect : str or csv.Dialect instance, default None
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    tupleize_cols : boolean, default False
        .. deprecated:: 0.21.0
           This argument will be removed and will always convert to MultiIndex

        Leave a list of tuples on columns as is (default is to convert to
        a MultiIndex on the columns)
    error_bad_lines : boolean, default True
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will dropped from the DataFrame that is
        returned.
    warn_bad_lines : boolean, default True
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.
    low_memory : boolean, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser)
    memory_map : boolean, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.

    Returns
    -------
    result : DataFrame or TextParser

None

In [8]:
# food_info.head(3)
# food_info.tail(4)
# print(food_info.columns)
print(food_info.shape)

(8618, 36)

In [3]:
col_names=food_info.columns.tolist()
print(col_names)
gram_columns=[]
for c in col_names:
    if c.endswith('(g)'):
        gram_columns.append(c)
gram_df=food_info[gram_columns]
print(gram_df)

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']
      Water_(g)  Protein_(g)  Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  \
0         15.87         0.85          81.11     2.11            0.06
1         15.87         0.85          81.11     2.11            0.06
2          0.24         0.28          99.48     0.00            0.00
3         42.41        21.40          28.74     5.11            2.34
4         41.11        23.24          29.68     3.18            2.79
5         48.42        20.75          27.68     2.70            0.45
6         51.80        19.80          24.26     3.68            0.46
7         39.28        25.18          29.20     3.28            3.06
8         37.10        24.04          33.82     3.71            1.33
9         37.65        23.37          30.60     3.60            4.78
10        38.20        23.76          32.11     3.36            2.57
11        79.79        11.12           4.30     1.41            3.38
12        79.64        10.69           3.85     1.20            4.61
13        81.01        10.34           0.29     1.71            6.66
14        81.24        10.45           2.27     1.27            4.76
15        82.48        12.39           1.02     1.39            2.72
16        54.44         5.93          34.24     1.32            4.07
17        41.56        24.99          27.80     4.22            1.43
18        55.22        14.21          21.28     5.20            4.09
19        37.92        25.60          31.14     3.79            1.55
20        13.44         9.65          29.51     4.75           42.65
21        41.46        24.94          27.44     3.94            2.22
22        33.19        29.81          32.34     4.30            0.36
23        48.42        20.05          27.25     3.79            0.49
24        41.01        24.48          30.28     3.55            0.68
25        50.01        22.17          22.35     3.28            2.19
26        48.38        21.60          24.64     2.91            2.47
27        53.78        24.26          15.92     3.27            2.77
28        45.54        24.58          19.72     3.80            6.36
29        41.77        23.41          30.04     3.66            1.12
...         ...          ...            ...      ...             ...
8588       2.00         6.60           0.90     2.00           88.60
8589      76.70         1.00           0.20     0.76           21.34
8590      83.10         0.30           0.20     0.29           16.30
8591       1.30         8.70          15.20     1.85           73.40
8592       5.00         7.12           5.46     1.22           81.19
8593       2.80        12.60           9.50     1.71           73.39
8594      81.60         0.50           0.20     0.52           17.18
8595      59.60        28.40           5.10     3.50            3.40
8596      14.50         4.40           7.50     0.80           72.90
8597      49.90        27.50          17.10     2.40            3.10
8598      21.70         0.00          77.80     0.40            0.30
8599       0.00         0.00         100.00     0.00            0.00
8600      23.90         0.00           0.00     0.00           76.10
8601      55.50         4.08          19.50     4.74           16.18
8602       9.00        11.30           2.10    13.90           63.70
8603       4.20         5.30           2.40     9.90           78.20
8604      84.40         0.00           0.00     0.22           15.38
8605      53.00         0.30           0.03     0.08           46.10
8606      54.66         0.41           0.20     0.35           44.38
8607      28.24         0.08           0.01     0.07           71.60
8608       6.80        10.08           3.00     5.70           74.42
8609      10.40         1.60           0.10     1.86           86.04
8610       6.84         0.81           0.90     6.80           84.66
8611       8.20        75.16           1.85     1.00           13.79
8612      81.90        16.40           0.30     1.40            0.00
8613      43.00        18.50          25.10    13.40            0.00
8614      70.25        20.54           0.84     2.97            5.41
8615      26.00         0.00           0.00     0.86           73.14
8616      79.20        16.10           1.40     1.30            2.00
8617      78.50        19.80           0.50     1.20            0.00

      Fiber_TD_(g)  Sugar_Tot_(g)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)
0              0.0           0.06      51.368       21.021        3.043
1              0.0           0.06      50.489       23.426        3.012
2              0.0           0.00      61.924       28.732        3.694
3              0.0           0.50      18.669        7.778        0.800
4              0.0           0.51      18.764        8.598        0.784
5              0.0           0.45      17.410        8.013        0.826
6              0.0           0.46      15.259        7.023        0.724
7              0.0            NaN      18.584        8.275        0.830
8              0.0           0.28      19.368        8.428        1.433
9              0.0            NaN      19.475        8.671        0.870
10             0.0           0.52      20.218        9.280        0.953
11             0.0           2.67       1.718        0.778        0.123
12             0.2           2.38       2.311        1.036        0.124
13             0.0           1.85       0.169        0.079        0.003
14             0.0           4.00       1.235        0.516        0.083
15             0.0           2.72       0.645        0.291        0.031
16             0.0           3.21      19.292        8.620        1.437
17             0.0           1.43      17.572        8.125        0.665
18             0.0           4.09      14.946        4.623        0.591
19             0.0           1.55      19.196        8.687        1.654
20             0.0            NaN      19.160        7.879        0.938
21             0.0           2.22      17.614        7.747        0.657
22             0.0           0.36      18.913       10.043        1.733
23             0.0           0.49      16.746        8.606        0.495
24             0.0           0.50      19.066        8.751        0.899
25             0.0           1.03      13.152        6.573        0.765
26             0.0           1.01      15.561        7.027        0.778
27             0.0           1.13      10.114        4.510        0.472
28             0.0           2.24      11.473        5.104        0.861
29             0.0           1.12      19.113        8.711        0.661
...            ...            ...         ...          ...          ...
8588           2.6           1.35       0.185        0.252        0.231
8589           1.6          11.36       0.072        0.028        0.041
8590           1.0          14.66       0.058        0.018        0.047
8591           5.7           0.53       2.837        6.341        5.024
8592           4.2          19.79       0.600        2.831        1.307
8593          14.2           0.54       1.415        4.085        3.572
8594           2.0          14.87       0.030        0.025        0.068
8595           0.0           1.33       3.304        1.351        0.180
8596           2.1          35.10       1.500        5.000        0.900
8597           0.0           1.23      10.867        4.844        0.509
8598           0.0           0.30      10.784       18.026       45.539
8599           0.0           0.00      14.367       48.033       33.033
8600           0.1          76.00       0.000        0.000        0.000
8601           0.0           8.21       7.996        3.108        7.536
8602          27.8          35.90       0.555        0.405        1.035
8603           6.1           0.70       0.984        1.154        0.131
8604           0.1            NaN       0.000        0.000        0.000
8605           0.8          45.30       0.009        0.001        0.008
8606           2.6          37.75       0.000        0.000        0.000
8607           0.0          24.53       0.003        0.001        0.009
8608          10.1           0.70       1.578        1.150        0.130
8609           0.9           2.90       0.018        0.032        0.050
8610           0.8           0.90       0.099        0.116        0.433
8611           0.6           0.00       0.272        0.156        0.810
8612           0.0           0.00       0.076        0.053        0.102
8613           0.0           0.00       7.148        8.320        6.210
8614           0.0           0.00       0.218        0.082        0.222
8615           0.0          73.20       0.000        0.000        0.000
8616           0.0           0.00       0.361        0.259        0.252
8617           0.0           0.00       0.127        0.088        0.170

[8618 rows x 10 columns]

In [9]:
max_calories=food_info['Energ_Kcal'].max()
print(max_calories)
food_info.sort_values('Sodium_(mg)',inplace=True, ascending=False)
print(food_info['Sodium_(mg)'])

902
276     38758.0
5814    27360.0
6192    26050.0
1242    26000.0
1245    24000.0
1243    24000.0
1244    23875.0
292     17000.0
1254    11588.0
5811    10600.0
8575     9690.0
291      8068.0
1249     8031.0
5812     7893.0
1292     7851.0
293      7203.0
4472     7027.0
4836     6820.0
1261     6580.0
3747     6008.0
1266     5730.0
4835     5586.0
4834     5493.0
1263     5356.0
1553     5203.0
1552     5053.0
1251     4957.0
1257     4843.0
294      4616.0
8613     4450.0
         ...
8153        NaN
8155        NaN
8156        NaN
8157        NaN
8158        NaN
8159        NaN
8160        NaN
8161        NaN
8163        NaN
8164        NaN
8165        NaN
8167        NaN
8169        NaN
8170        NaN
8172        NaN
8173        NaN
8174        NaN
8175        NaN
8176        NaN
8177        NaN
8178        NaN
8179        NaN
8180        NaN
8181        NaN
8183        NaN
8184        NaN
8185        NaN
8195        NaN
8251        NaN
8267        NaN
Name: Sodium_(mg), Length: 8618, dtype: float64

In [10]:
import numpy as np
titanic_surivival=pandas.read_csv('titanic_train.csv')
titanic_surivival.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
age=titanic_surivival['Age']
#print(age.loc[0:10])
age_is_null=pandas.isnull(age)
# print(age_is_null)
age_null_true=age[age_is_null]
# print(age_null_true)
print(len(age_null_true))
good_ages=titanic_surivival['Age'][age_is_null==False]
correct_mean_age=sum(good_ages)/len(good_ages)
print(correct_mean_age)

177
29.69911764705882

In [17]:
passenger_survival=titanic_surivival.pivot_table(index='Pclass',values='Survived',aggfunc=np.mean)
print(passenger_survival)

        Survived
Pclass
1       0.629630
2       0.472826
3       0.242363

In [18]:
port_stats=titanic_surivival.pivot_table(index='Embarked',values=['Fare','Survived'],aggfunc=np.sum)
print(port_stats)

                Fare  Survived
Embarked
C         10072.2962        93
Q          1022.2543        30
S         17439.3988       217

In [ ]:
def hundredth_row():